-- GitHub 통합: Issue/Branch/PR 연결 정보 + Branch DB 영구 저장
-- 적용 위치: Supabase SQL Editor
--
-- 목적:
-- - items 테이블에 Branch 정보 컬럼 추가 (API 호출 최소화)
-- - ItemDetailPanel에서 로딩 표시 없이 DB 정보 즉시 표시
-- - 백그라운드에서 API 호출로 최신 정보 갱신
-- - item_github_pull_requests: PR 연결 스냅샷 저장

-- Step 1: items 테이블 확장 (Branch 정보 컬럼 추가)
alter table public.items add column if not exists github_linked_branch_name text;
alter table public.items add column if not exists github_linked_branch_url text;
alter table public.items add column if not exists github_branch_source text default 'none';
alter table public.items add column if not exists github_branch_updated_at timestamptz;

create table if not exists public.item_github_pull_requests (
  id bigint generated by default as identity primary key,
  item_id uuid not null,
  repo_full_name text not null,
  pull_number integer not null,
  pull_url text not null,
  github_pull_request_id bigint not null unique,
  pull_title_snapshot text not null,
  pull_state_snapshot text not null default 'open',
  head_ref text,
  base_ref text,
  is_draft boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint item_github_pull_requests_unique_repo_number unique (repo_full_name, pull_number)
);

create index if not exists item_github_pull_requests_item_id_idx
  on public.item_github_pull_requests (item_id, created_at desc);

create index if not exists item_github_pull_requests_repo_head_idx
  on public.item_github_pull_requests (repo_full_name, head_ref);

alter table public.item_github_pull_requests enable row level security;

create policy "item_github_pull_requests_select_authenticated"
  on public.item_github_pull_requests
  for select
  to authenticated
  using (true);

create policy "item_github_pull_requests_insert_service_role"
  on public.item_github_pull_requests
  for insert
  to service_role
  with check (true);

create policy "item_github_pull_requests_update_service_role"
  on public.item_github_pull_requests
  for update
  to service_role
  using (true)
  with check (true);
